### ISSUE TITLE
Error while downloading data files: 404 Not found

### ISSUE THREAD

**Issue by MadhurimaGhose05** [millie-crowther/fusion#1]
![screenshot from 2018-09-19 15-52-10](https://user-images.githubusercontent.com/32602347/45747614-01369900-bc24-11e8-8bb6-c50ec9761906.png)

**Comment by saurabheights** [comment]
See this issue: https://github.com/mihaibujanca/dynamicfusion/issues/59#issuecomment-399221580
The data is shared by authors but in the same issue, one has reported it to be in different format. Thus, it may not work.

Hope it helps.

**Comment by MadhurimaGhose05** [comment]
> See this issue: [mihaibujanca/dynamicfusion#59 (comment)](https://github.com/mihaibujanca/dynamicfusion/issues/59#issuecomment-399221580)
> The data is shared by authors but in the same issue, one has reported it to be in different format. Thus, it may not work.
> 
> Hope it helps.

Thanks @saurabheights ! I am able to download the Files now.
